queue_rules:
  - name: duplicated default from Auto-merge dependabot
    queue_conditions:
      - "#approved-reviews-by>=1"
      - author=dependabot[bot]
    merge_conditions: []
    merge_method: squash
  - name: duplicated default from Automatic merge when Github conditions pass
    queue_conditions:
      - "#approved-reviews-by>=1"
      - base=main
      - label!=work-in-progress
      - label!='changes requested'
      - author~=^(?:(?!dependabot).)*$
    merge_conditions: []
    commit_message_template: |
      {{ title }} (#{{ number }})
      {{ body }}
    merge_method: squash

pull_request_rules:
  - name: Have Dependabot rebase when conflict at head of queue
    # It's not unusual for there to be a conflict between subsequent dependabot
    # requests, dependabot knows best how to solve these.
    conditions:
      # Also covered by Github protections but this reduces noise from mergify.
      - "#approved-reviews-by>=1"
      - author=dependabot[bot]
      - queue-position=0
      - conflict
    actions:
      comment:
        message: "@dependabot rebase"

  - name: Approve PRs by tora-pan after they are marked ready
    conditions:
      - author=tora-pan
      - label=self-approved
    actions:
      review:
        type: APPROVE
        message: "tora-pan says it's fine so hopefully it's fine!"

  - name: Auto-merge dependabot + Automatic merge when Github conditions pass
    conditions: []
    actions:
      queue:
